[package]
name = "ray_casting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ang = "0.6.0"
input = "0.8.2"
libc = "0.2.140"
sdl2 = { version = "0.35.2", features = ["image"] }
